source 'https://supermarket.chef.io'

cookbook 'cas_magento',
    tag: '~> 1.0',
    git: 'https://github.com/cascadia-cookbooks/magento.git'

cookbook 'cas_cron',
    tag: '~> 1.0',
    git: 'https://github.com/cascadia-cookbooks/cron.git'

cookbook 'packages', '~> 1.0'
cookbook 'selinux', '~> 1.0'
cookbook 'sudo', '~> 3.5'
cookbook 'user', '~> 0.7'
cookbook 'yum-epel', '~> 2.1'
